-- MySQL Script generated by MySQL Workbench
-- Wed May 14 02:59:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `stu_email` VARCHAR(45) NOT NULL,
  `pass_hash` VARCHAR(64) NOT NULL,
  `role` ENUM('student', 'moderator', 'admin') NOT NULL DEFAULT 'student',
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Posts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(5000) NULL,
  `visibility` ENUM('public', 'private', 'friends_only') NOT NULL DEFAULT 'public',
  `post_type` ENUM('text', 'media', 'poll') NOT NULL DEFAULT 'text',
  `created_at` TIMESTAMP NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `user_id`),
  INDEX `fk_Posts_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flairs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Flairs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Flairs` (
  `flair_id` INT NOT NULL AUTO_INCREMENT,
  `flair_type` ENUM('student', 'moderator', 'admin') NOT NULL DEFAULT 'student',
  `flair_name` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`flair_id`, `post_id`),
  INDEX `fk_Flairs_Posts1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_Flairs_Posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`Posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post_Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Post_Comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Post_Comments` (
  `post_comment_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(5000) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`post_comment_id`, `post_id`, `user_id`),
  INDEX `fk_Comment_Posts1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_Post_Comments_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`Posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Comments_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post_Votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Post_Votes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Post_Votes` (
  `post_vote_id` INT NOT NULL AUTO_INCREMENT,
  `vote_type` ENUM('upvote', 'downvote') NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`post_vote_id`, `post_id`, `user_id`),
  INDEX `fk_Post_Votes_Posts1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_Post_Votes_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Votes_Posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`Posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Votes_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Saves` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Saves` (
  `saved_at` TIMESTAMP NOT NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`saved_at`, `post_id`, `user_id`),
  INDEX `fk_Saves_Posts1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_Saves_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Saves_Posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`Posts` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saves_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CompanionChatSession`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CompanionChatSession` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CompanionChatSession` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `started_at` TIMESTAMP NOT NULL,
  `ended_at` TIMESTAMP NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`session_id`, `user_id`),
  INDEX `fk_CompanionChatBotSession_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_CompanionChatBotSession_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ChatbotCompanion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ChatbotCompanion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ChatbotCompanion` (
  `avatar_id` INT NOT NULL AUTO_INCREMENT,
  `avatar_name` VARCHAR(50) NOT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `user_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  PRIMARY KEY (`avatar_id`, `user_id`, `session_id`),
  INDEX `fk_ChatbotCompanion_Users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_ChatbotCompanion_CompanionChatSession1_idx` (`session_id` ASC) VISIBLE,
  CONSTRAINT `fk_ChatbotCompanion_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChatbotCompanion_CompanionChatSession1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`CompanionChatSession` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CompanionMessage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CompanionMessage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CompanionMessage` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `sender` ENUM('sender', 'companion') NOT NULL,
  `message` VARCHAR(9999) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `session_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`message_id`, `session_id`, `user_id`),
  INDEX `fk_CompanionMessage_CompanionChatSession1_idx` (`session_id` ASC, `user_id` ASC) VISIBLE,
  CONSTRAINT `fk_CompanionMessage_CompanionChatSession1`
    FOREIGN KEY (`session_id` , `user_id`)
    REFERENCES `mydb`.`CompanionChatSession` (`session_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calendar_Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Calendar_Event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Calendar_Event` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(100) NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `user_id`),
  INDEX `fk_Calendar_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Calendar_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_Votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users_Votes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users_Votes` (
  `user_vote_id` INT NOT NULL AUTO_INCREMENT,
  `vote_type` ENUM('upvote', 'downvote') NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_vote_id`, `user_id`),
  INDEX `fk_Users_Votes_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Votes_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_Comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_Comments` (
  `user_comment_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(5000) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_comment_id`, `user_id`),
  INDEX `fk_User_Comments_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Comments_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PostC_Votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PostC_Votes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PostC_Votes` (
  `postc_vote_id` INT NOT NULL AUTO_INCREMENT,
  `vote_type` ENUM('upvote', 'downvote') NULL,
  `post_comment_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`postc_vote_id`, `post_comment_id`, `post_id`),
  INDEX `fk_PostC_Votes_Post_Comments1_idx` (`post_comment_id` ASC, `post_id` ASC) VISIBLE,
  CONSTRAINT `fk_PostC_Votes_Post_Comments1`
    FOREIGN KEY (`post_comment_id` , `post_id`)
    REFERENCES `mydb`.`Post_Comments` (`post_comment_id` , `post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
