# Generated by Django 5.2.2 on 2025-06-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='content',
            new_name='profile_feedback',
        ),
        migrations.AddField(
            model_name='usercomments',
            name='profile_downvote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='profile_upvote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
