# Generated by Django 5.2.2 on 2025-07-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0002_rename_content_usercomments_profile_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='reminder',
        ),
    ]
