# Generated by Django 5.2.2 on 2025-07-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0003_remove_calendarevent_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='profile_downvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='profile_upvote',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UsersVotes',
        ),
    ]
