# Generated by Django 5.2.2 on 2025-07-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0004_alter_usercomments_profile_downvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
