# Generated by Django 5.2.2 on 2025-07-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0006_alter_companionmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
