# Generated by Django 5.2.2 on 2025-07-06 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0007_alter_posts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='commenter_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
