# Generated by Django 5.2.2 on 2025-07-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0008_usercomments_commenter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='user',
            new_name='commenter',
        ),
        migrations.RenameField(
            model_name='usercomments',
            old_name='commenter_email',
            new_name='user_email',
        ),
    ]
