# Generated by Django 5.2.2 on 2025-07-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0009_rename_user_usercomments_commenter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='user_email',
            new_name='profile_user_email',
        ),
    ]
