# Generated by Django 5.2.2 on 2025-07-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0010_rename_user_email_usercomments_profile_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='profile_user_email',
            field=models.CharField(max_length=40),
        ),
    ]
