# Generated by Django 5.2.2 on 2025-07-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0011_alter_usercomments_profile_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomments',
            name='profile_downvote',
        ),
    ]
