# Generated by Django 5.2.2 on 2025-07-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0012_remove_usercomments_profile_downvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/blank_profile.png', null=True, upload_to='images/'),
        ),
    ]
