# Generated by Django 5.2.2 on 2025-07-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0013_alter_users_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('flair_id', models.AutoField(primary_key=True, serialize=False)),
                ('flair_color', models.CharField(max_length=30)),
                ('flair_name', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flair',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='pfp/blank_profile.png', null=True, upload_to='pfp/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='flair',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='FYP_TestApp.flair'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Flairs',
        ),
    ]
