# Generated by Django 5.2.2 on 2025-07-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0014_flair_alter_users_image_posts_flair_delete_flairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='visibility',
        ),
    ]
