# Generated by Django 5.2.2 on 2025-07-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0015_remove_posts_post_type_remove_posts_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcvotes',
            name='vote_type',
        ),
        migrations.RemoveField(
            model_name='postvotes',
            name='vote_type',
        ),
        migrations.AddField(
            model_name='postcvotes',
            name='postc_upvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postvotes',
            name='post_upvote',
            field=models.BooleanField(default=False),
        ),
    ]
