# Generated by Django 5.2.2 on 2025-07-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0016_remove_postcvotes_vote_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='content',
            field=models.TextField(),
        ),
    ]
