# Generated by Django 5.2.2 on 2025-07-09 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0017_alter_postcomments_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcvotes',
            name='post',
        ),
        migrations.AddField(
            model_name='postcvotes',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
