# Generated by Django 5.2.2 on 2025-07-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0019_reportcomment_reportpost'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportcomment',
            table='report_comment',
        ),
        migrations.AlterModelTable(
            name='reportpost',
            table='report_post',
        ),
    ]
