# Generated by Django 5.2.2 on 2025-07-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0021_reportuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportuser',
            old_name='target_user',
            new_name='target',
        ),
    ]
