# Generated by Django 5.2.2 on 2025-07-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isSeen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
