# Generated by Django 5.2.2 on 2025-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0024_notification_isseen_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='vote',
            field=models.BooleanField(null=True),
        ),
    ]
