# Generated by Django 5.2.2 on 2025-07-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0027_appeals'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appeals',
            table='appeals',
        ),
    ]
