# Generated by Django 5.2.2 on 2025-07-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0028_alter_appeals_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionFAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='companionchatsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companionmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='companionmessage',
            name='user',
        ),
        migrations.CreateModel(
            name='CompanionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('keyword', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYP_TestApp.companionfaqcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatbotCompanion',
        ),
        migrations.DeleteModel(
            name='CompanionChatSession',
        ),
        migrations.DeleteModel(
            name='CompanionMessage',
        ),
    ]
