# Generated by Django 5.2.2 on 2025-07-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0029_companionfaqcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companionfaq',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
