# Generated by Django 5.2.2 on 2025-07-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0030_rename_keyword_companionfaq_keywords'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companionfaq',
            table='companion_faq',
        ),
        migrations.AlterModelTable(
            name='companionfaqcategory',
            table='companion_faq_category',
        ),
    ]
