# Generated by Django 5.2.2 on 2025-07-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_TestApp', '0031_alter_companionfaq_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='isSeen',
            new_name='is_seen',
        ),
    ]
